### ISSUE TITLE
#err_require_esm issue

### ISSUE THREAD

**Issue by quan-unizen** [curvefi/curve-js#202]
Hi guys, 

I m trying to install the lib but always get issue like this?
<img width="2206" alt="image" src="https://github.com/curvefi/curve-js/assets/88375848/7ce0b4cb-c762-4929-a781-615eafd6073d">

Any idea to fix it?

**Comment by ZiggStardust** [comment]
i've got a similar issue with using this lib on vercel 

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/@curvefi/api/lib/external-api.js' imported from /var/task/node_modules/@curvefi/api/lib/pools/utils.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:332:11)
    at moduleResolve (node:internal/modules/esm/resolve:995:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12)
    at defaultResolve (node:internal/modules/esm/resolve:1181:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/pool'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by HadiKhai** [comment]
I am also experiencing the same issue, I'm trying to integrate @curvefi/api in my nestjs backend (within an nx monorepo) and I got this error

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/hadikhairallah/WebstormProjects/adapter-mono/apps/curve/webpack.config.js from /Users/hadikhairallah/WebstormProjects/{projectname}/node_modules/@nx/webpack/src/utils/webpack/resolve-user-defined-webpack-config.js not supported.
webpack.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename webpack.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/hadikhairallah/WebstormProjects/{projectname}/apps/curve/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at resolveUserDefinedWebpackConfig (/Users/hadikhairallah/WebstormProjects/{projectname}/node_modules/@nx/webpack/src/utils/webpack/resolve-user-defined-webpack-config.js:19:16)
    at getWebpackConfigs (/Users/hadikhairallah/WebstormProjects/{projectname}/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:24:110)
    at webpackExecutor (/Users/hadikhairallah/WebstormProjects/{projectname}/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:99:27)
    at webpackExecutor.next (<anonymous>)
    at /Users/hadikhairallah/WebstormProjects/{projectname}/node_modules/@nx/js/src/executors/node/node.impl.js:199:44 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.0
```

**Comment by TechGeorgii** [comment]
@HadiKhai @MetaMmodern were you able to get it working? Same error, console Nodejs app.

**Comment by MetaMmodern** [comment]
> @HadiKhai @MetaMmodern were you able to get it working? Same error, console Nodejs app.

No

**Comment by AndreMiras** [comment]
It looks like that behavior started happening between @curvefi/api@2.31.0 and @curvefi/api@2.31.1
https://github.com/curvefi/curve-js/compare/v2.30.0...v2.30.1
It's not exactly what I'm expecting from a patch upgrade :see_no_evil: 

More specifically it may have been introduced in this pull request https://github.com/curvefi/curve-js/pull/151 and possibly one of these changes:
- package.json:
  - "type": "module"
- tsconfig.json
  - "module": "ESNext"
  - "target": "es2020"

**Comment by AndreMiras** [comment]
My workaround (tested with both node 18 and node 20) is:
```
node --import "data:text/javascript,import {register} from 'node:module'; import {pathToFileURL} from 'node:url'; register('ts-node/esm', pathToFileURL('./'))" my-script.ts
```
More info there https://github.com/TypeStrong/ts-node/issues/1007#issuecomment-1864819206
Kinda ugly, but that did it for me for my dev setup.

**Comment by TechGeorgii** [comment]
Thanks guys. I was able to solve it two ways: first when running by `tsx` like `npx tsx src/index.ts` (previously I used `ts-node`. Second – I set up webpack config and it built my app and it ran without problems.
